Traceback (most recent call last):
  File "c:\users\katie\onedrive\documents\coding\automate the boring stuff book\ch 11\practicequestions.py", line 46, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
